[build]
  functions = "netlify/functions"  # Adjust this if your functions are elsewhere
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200